[PATCH] prism94 build fix
init_wds is being instantiated in both isl_ioctl.c and islpci_eth.c, causing
linkage errors.

drivers/net/wireless/prism54/islpci_mgt.o(.rodata+0x198): In function `islpci_mgmt_rx_fill':
/usr/src/25/drivers/net/wireless/prism54/islpci_mgt.c:154: multiple definition of `init_wds'
drivers/net/wireless/prism54/islpci_eth.o(.rodata+0x1c8):/usr/src/25/include/linux/skbuff.h:815: first defined here

Signed-off-by: Andrew Morton <akpm@osdl.org>