[PATCH] fix sbni.c compile with gcc 3.3
sbni.c in 2.6.0-test5 fails to compile with gcc 3.3 with the following
error:

<--  snip  -->

...
  CC      drivers/net/wan/sbni.o
...
drivers/net/wan/sbni.c: In function `calc_crc32':
drivers/net/wan/sbni.c:1568: error: asm-specifier for variable `_crc'
conflicts with asm clobber list
make[3]: *** [drivers/net/wan/sbni.o] Error 1

<--  snip  -->

Below is the patch by Margit Schubert-White to fix this issue (it is
already in 2.4).

cu
Adrian